[package]
name = "mla"
version = "2.1.0"
authors = ["ANSSI <opensource@ssi.gouv.fr>"]
edition = "2024"
license = "LGPL-3.0-only"
description = "Multi Layer Archive - A pure rust encrypted and compressed archive file format"
homepage = "https://github.com/ANSSI-FR/MLA"
repository = "https://github.com/ANSSI-FR/MLA"
readme = "../README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { version = "0.10", default-features = false, features = ["sys_rng", "std", "thread_rng"]}
rand_chacha = { version = "0.10", default-features = false}
brotli = { version = "9.0", default-features = false, features = ["std"]}
bitflags = { version = "2.13", default-features = false }
# Crypto needs
hybrid-array = { version = "0.4", default-features = false}
ghash = { version = "0.6", default-features = false}
aes = { version = "0.9", default-features = false}
ctr = { version = "0.10", default-features = false}
subtle = { version = "2.6", default-features = false}
digest = { version = "0.11", default-features = false}
# ECC
x25519-dalek = { version = "3.0", default-features = false, features = ["zeroize", "static_secrets"]}
hkdf = { version = "0.13", default-features = false}
sha2 = { version = "0.11", default-features = false}
zeroize = { version = "1.9", default-features = false}
# Post-quantum
ml-kem = { version = "0.3", default-features = false, features = ["zeroize"] }
hpke = { version = "0.14", default-features = false, features = ["alloc", "x25519", "aes"] }
curve25519-dalek = { version = "5.0", default-features = false}
ed25519-dalek = { version = "3.0", default-features = false, features = ["digest", "fast", "rand_core", "zeroize"] }
ml-dsa = { version = "0.1", default-features = false, features = ["rand_core", "zeroize", "alloc"] }

[lints]
workspace = true

[dev-dependencies]
hex-literal = { version = "1.1", default-features = false}
aes-gcm = { version = "0.11", default-features = false, features = ["aes"]}
aead = { version = "0.6", default-features = false, features = ["alloc"]}
criterion = { version = "0.8", default-features = false, features = ["html_reports"]}
hex = { version = "0.4", default-features = false, features = ["alloc"]}
static_assertions = { version = "1.1", default-features = false }

[features]
default = []
send = []

[[bench]]
name = "bench_archive"
harness = false
