name: Benchmark PR

permissions:
  contents: read
  pull-requests: write

on: workflow_dispatch

jobs:
  runBenchmark:
    name: Criterion benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: boa-dev/criterion-compare-action@v3.2.4
        with:
          branchName: ${{ github.base_ref }}
          benchName: "bench_archive"
          token: ${{ secrets.GITHUB_TOKEN }}