name: Benchmark PR

permissions:
  contents: read
  pull-requests: write

on: workflow_dispatch

jobs:
  runBenchmark:
    name: Criterion benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: boa-dev/criterion-compare-action@adfd3a94634fe2041ce5613eb7df09d247555b87 # v3.2.4
        with:
          branchName: ${{ github.base_ref }}
          benchName: "bench_archive"
          token: ${{ secrets.GITHUB_TOKEN }}