name: Deploy mdBook to GitHub Pages

permissions: {}

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions-rs/toolchain@b2417cde72dcf67f306c0ae8e0828a81bf0b189f # v1.0.6
        with:
          toolchain: stable

      - name: Install mdbook and mdbook-katex
        uses: actions-rs/cargo@ae10961054e4aa8b4aa7dffede299aaf087aa33b # v1.0.1
        with:
          command: install
          args: mdbook mdbook-katex --locked

      # GitHub Flavored Markdown's ```math blocks are not supported by GitHub Pages,
      # but KaTeX requires $$ math delimiters. This step converts ```math blocks to $$ blocks.
      - name: Preprocess markdown files - convert ```math blocks to $$ blocks
        run: |
          find ./doc/src -name '*.md' -exec sh -c '
            awk '\''
              /^```math$/ { in_math=1; print "$$"; next }
              /^```$/ && in_math { in_math=0; print "$$"; next }
              { print }
            '\'' "$1" > tmp && mv tmp "$1"
          ' sh {} \;

      - name: Build the book
        run: mdbook build ./doc

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: ./doc/book

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages # GitHub automatically uses this environment for Pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write  # Needed for gh-pages push
      id-token: write  # Needed for GitHub Pages deployment

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
