name: Ensure repository healthy state over time

permissions:
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:


env:
  CARGO_TERM_COLOR: always

jobs:
  bindings-headers-sync:
    # Assert .h and .hpp bindings files are the ones generated
    runs-on: ubuntu-24.04
    container: rust@sha256:ecbe59a8408895edd02d9ef422504b8501dd9fa1526de27a45b73406d734d659 # v1.93.1 : pin to known-good previous stable release for increased stability and security

    steps: 
    - uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
      with:
        egress-policy: audit
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false    
    - name: Install cbindgen
      run: cargo install cbindgen
    - name: Test C header
      working-directory: bindings/C
      run: cbindgen --config cbindgen_c.toml | diff - mla.h
    - name: Test C++ header
      working-directory: bindings/C
      run: cbindgen --config cbindgen_cpp.toml | diff - mla.hpp

  changelog-format:
    # Ensure CHANGELOGs respect the KeepAChangelog format
    strategy:
      matrix:
        changelog: [mla, mlar]
        include:
          - changelog: mla
            path: mla
          - changelog: mlar
            path: mlar
          - changelog: bindings-c
            path: bindings/C
          - changelog: bindings-python
            path: bindings/python
    runs-on: ubuntu-24.04

    steps:
    - uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
      with:
        egress-policy: audit    
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - name: Get ${{ matrix.changelog }} Changelog Entry
      uses: mindsers/changelog-reader-action@32aa5b4c155d76c94e4ec883a223c947b2f02656 # v2.2.3
      id: changelog_reader
      with:
        # Check format for the last 10 entries
        validation_depth: 10
        path: ${{ matrix.path }}/CHANGELOG.md
    - name: Information
      env:
          CL_VERSION: ${{ steps.changelog_reader.outputs.version }}
          CL_STATUS: ${{ steps.changelog_reader.outputs.status }}
          CL_CHANGES: ${{ steps.changelog_reader.outputs.changes }}
      run: |
          echo -en "\e[1mVersion\e[0m"
          echo "${CL_VERSION}"
          echo -e "\e[1mStatus\e[0m"
          echo "${CL_STATUS}"
          echo -en "\e[1mBody\e[0m"
          echo "${CL_CHANGES}"
